# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(blank=True, max_length=30)),
                ('enabled', models.NullBooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appRoles', models.ManyToManyField(blank=True, related_name='appRoles', to='users.AppRole')),
                ('appUsers', models.ManyToManyField(blank=True, related_name='appUsers', to='users.AppUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='my_groups', to='users.Group'),
        ),
        migrations.AddField(
            model_name='approle',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='users.Group'),
        ),
    ]
