# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0005_auto_20160704_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerOrders', to='mystore.Customer'),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerReviews', to='mystore.Customer'),
        ),
    ]
